title: Divorced in Virginia
description: A practical guide to divorce in Virginia
author: J Henry
email: j.henry@jhenrycode.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude files/folders
exclude:
  - .gitignore
  - README.md
  - node_modules
